### ISSUE TITLE
Bugs en busqueda en la computadora

### ISSUE THREAD

**Issue by NatooLex** [QuetzalcoutlDev/Alone#1]
#bug En decisiones "bipolaridad" y "depresión"
![image](https://user-images.githubusercontent.com/55214351/182268858-d8314bbf-d68e-438a-9243-b32b0b6a20f8.png)

**Comment by QuetzalcoutlDev** [comment]
Estoy resolviendolo 👍

**Comment by QuetzalcoutlDev** [comment]
Closed #1
